codecoretest/fulltime/week4/day 17 Rails/blog/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"
  get "/home" => "home#index"
  # get "/admin/questions" => "admin/questions#index"
  get "/about" => "home#about", as: :about

  namespace :admin do
    resources :questions

  end

end

codecoretest/fulltime/week4/day 17 Rails/blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

codecoretest/fulltime/week4/day 17 Rails/blog/app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < ApplicationController
  def index
  end
end

codecoretest/fulltime/week4/day 17 Rails/blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
end

codecoretest/fulltime/week4/day 17 Rails/blog/app/controllers/home_controller.rb
class HomeController < ApplicationController
end

codecoretest/fulltime/week4/day 17 Rails/blog/app/helpers/admin/questions_helper.rb
module Admin::QuestionsHelper
end

codecoretest/fulltime/week4/day 17 Rails/blog/app/helpers/application_helper.rb
module ApplicationHelper
end

codecoretest/fulltime/week4/day 17 Rails/blog/app/helpers/home_helper.rb
module HomeHelper
end

codecoretest/fulltime/week4/day 17 Rails/blog/app/views/admin/questions/index.html.erb
<h3>questions</h3>

codecoretest/fulltime/week4/day 17 Rails/blog/app/views/home/about.html.erb
<h1>About us </h1>
<img src="images/icon-kepler.png" alt="Kepler Photo" />

codecoretest/fulltime/week4/day 17 Rails/blog/app/views/home/index.html.erb
<h1>Home</h1>

codecoretest/fulltime/week4/day 17 Rails/blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <li class="active"><a href="<%= root_path %>"> HOME </a></li>
    <li><%= link_to("About US", about_path) %></li>
    <li><%= link_to("Questions", admin_questions_path) %></li>

    <div id="main-container" class="container">
      <div class="row">
        <div class="col-xs-12">
          <%= yield %>
        </div>
      </div>
    </div>

  </body>
</html>

rails g model question title:string body:text