codecoretest/fulltime/week4/day 17 Rails/amazon/config/routes.rb
Rails.application.routes.draw do
  get "/home" => "home#index"
  get "/about_us" => "home#about_us", as: :about_us
  get "/contact" => "contact#contact", as: :contact
  post "/contact" => "contact#thankyou",  as: :thankyou
  root "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :products do
    # get "/questions/new" => "questions#new", as: :new_question
    # post "/questions" => "questions#create", as: :questions
    # get "/questions/:id" => "questions#show",   as: :question
    # get "/questions" => "questions#index"
    # get "/questions/:id/edit" => "questions#edit",   as: :edit_question
    # patch "/questions/:id" => "questions#update"
    # delete "/questions/:id" => "questions#destroy"
    resources :reviews, only: [:index, :create, :destroy]
  end
end

codecoretest/fulltime/week4/day 17 Rails/amazon/app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy
end

codecoretest/fulltime/week4/day 17 Rails/amazon/app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :reviews, dependent: :destroy

  validates :title, presence: true, uniqueness: true
  validates :price, presence: true#, #numericality: { greater_than: 0, less_than: 1000 }
  validates :description, presence: true

end

codecoretest/fulltime/week4/day 17 Rails/amazon/app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  # validates :body , presence: true, uniqueness: {scope: :review_id}
  validates :star, :inclusion => 1..5
end

codecoretest/fulltime/week4/day 17 Rails/amazon/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

codecoretest/fulltime/week4/day 17 Rails/amazon/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

codecoretest/fulltime/week4/day 17 Rails/amazon/app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def contact

  end

  def thankyou
    @name = params[:name]

  end
end

codecoretest/fulltime/week4/day 17 Rails/amazon/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about_us

  end

end

codecoretest/fulltime/week4/day 17 Rails/amazon/app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def new

    @product = Product.new


  end

  def index
    @products = Product.order(created_at: :desc).last(20)
  end

  def show
    @product = Product.find params[:id]
    @review = Review.new
    @category = @product.category

  end

  def edit
    @product = Product.find params[:id]

  end

  def update
    @product = Product.find params[:id]
    if @product.update question_params
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def create

   product_params  = question_params
    @product       = Product.new product_params

    if @product.save
      redirect_to product_path(@product)
    else
      render :new
    end

  end

  def destroy
    product = Product.find params[:id]
    product.destroy
    redirect_to products_path
  end

  private

  def question_params
    params.require(:product).permit([:title, :description, :price, :category_id])
    # params.require(:question).permit([:title, :body])
  end





end

codecoretest/fulltime/week4/day 17 Rails/amazon/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  
end

codecoretest/fulltime/week4/day 17 Rails/amazon/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @review = Review.new params.require(:review).permit(:body,:star)
    @product = Product.find params[:product_id]
    @review.product = @product

    if @review.save
    # we redirect to the question show page
      redirect_to product_path(@product), notice: "Answer created!"
    else
      flash[:alert] = "please fix errors below"
      render "/products/show"
    end

  end

  def destroy
    # render json: params
    q = Product.find params[:product_id]
    a = Review.find params[:id]
    a.destroy
    redirect_to product_path(q), notice: "Answer deleted"



  end
end

codecoretest/fulltime/week4/day 17 Rails/amazon/app/helpers/categories_helper.rb
module CategoriesHelper
end

codecoretest/fulltime/week4/day 17 Rails/amazon/app/helpers/contact_helper.rb
module ContactHelper
end

codecoretest/fulltime/week4/day 17 Rails/amazon/app/helpers/products_helper.rb
module ProductsHelper
end

codecoretest/fulltime/week4/day 17 Rails/amazon/app/helpers/questions_helper.rb
module QuestionsHelper
end

codecoretest/fulltime/week4/day 17 Rails/amazon/app/helpers/reviews_helper.rb
module ReviewsHelper
end

codecoretest/fulltime/week4/day 17 Rails/amazon/app/views/contact/contact.html.erb
<h3>Contact</h3>
<%= form_tag thankyou_path do %>
  <div>
    <%= label_tag :name %>
    <%= text_field_tag :name %>
  </div>
  <div>
    <%= label_tag :message %>
    <%= text_area_tag :message %>
  </div>
  <%= submit_tag "Contact US!" %>

<% end %>

codecoretest/fulltime/week4/day 17 Rails/amazon/app/views/contact/thankyou.html.erb
<h4>Thank you <%= @name %></h4>

codecoretest/fulltime/week4/day 17 Rails/amazon/app/views/home/about_us.html.erb
<h3>About us </h3>

codecoretest/fulltime/week4/day 17 Rails/amazon/app/views/home/index.html.erb
<h1>HOME</h1>

codecoretest/fulltime/week4/day 17 Rails/amazon/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Amazon</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div id="main-container" class="container">
        <div class="row">
          <nav class="navbar navbar-light bg-faded">
            <button class="navbar-toggler hidden-sm-up" type="button" data-toggle="collapse" data-target="#navbar-header" aria-controls="navbar-header">
              &#9776;
            </button>
            <div class="collapse navbar-toggleable-xs" id="navbar-header">
              <a class="navbar-brand" href="#">Navbar</a>
              <ul class="nav navbar-nav">
                <li class="nav-item active"><a class="nav-link" href="<%= root_path %>"> HOME </a></li>
                <li class="nav-item"><%= link_to("About US", about_us_path, class:"nav-link") %></li>
                <li class="nav-item"><%= link_to("Contact", contact_path, class:"nav-link") %></li>
                <li class="nav-item"><%= link_to("Products", products_path, class:"nav-link") %></li>
                <li class="nav-item"><%= link_to("New Product", new_product_path, class:"nav-link") %></li>
              </ul>

            </div>
          </nav> <!-- /navbar -->


            <!-- <nav class="navbar navbar-default">
              <div class="container-fluid">
                <div class="navbar-header">
                  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </button>
                  <a class="navbar-brand" href="<%= root_path %>">Amazon </a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                  <ul class="nav navbar-nav">

                    <li class="active"><a href="<%= root_path %>"> HOME </a></li>
                    <li><%= link_to("About US", about_us_path) %></li>
                    <li><%= link_to("Contact", contact_path) %></li>
                    <li><%= link_to("Products", products_path) %></li>
                    <li><%= link_to("New Product", new_product_path) %></li>

                  </ul>

                </div>
              </div>
            </nav> -->

            

            <% if flash[:notice] %>
              <div class="alert alert-success" role="alert">
                <%= flash[:notice] %>
              </div>
            <% end %>

            <% if  flash[:alert] %>
              <div class="alert alert-danger" role="alert">
                <%= flash[:alert]  %>
              </div>
            <% end %>

            <%= yield %>

          </div>
        </div>
      </div>
    </div>


  </body>
</html>

codecoretest/fulltime/week4/day 17 Rails/amazon/app/views/products/create.html.erb
<h1>ALL </h1>

codecoretest/fulltime/week4/day 17 Rails/amazon/app/views/products/edit.html.erb
<h1>Edit Question</h1>

<div class="alert alert-success" role="alert">
<%= @product.errors.full_messages.join(", ") %>
</div>
 <%= form_for @product do |f| %>
   <div class="form-group row">
     <%= f.label(:title, class: "col-xs-2 col-form-label") %>
       <div class="col-xs-10">
       <%= f.text_field :title %>
    </div>
   </div>
   <div class="form-group row">
     <%= f.label(:description, class: "col-xs-2 col-form-label") %>
      <div class="col-xs-10">
       <%= f.text_area(:description, class: "form-control")%>
       </div>
   </div>
   <div class="form-group row">
     <%= f.label(:price, class: "col-xs-2 col-form-label") %>
     <div class="col-xs-10">
       <%= f.text_field :price %>
     </div>
   </div>

   <div class="form-group row">
     <%= f.label(:category, class: "col-xs-2 col-form-label") %>
     <div class="col-xs-10">
       <%= f.collection_select :category_id, Category.all, :id , :title  %>
     </div>
   </div>
   <%= f.submit ("Edit Product"), {class: "btn btn-danger col-xs-offset-2"}%>

 <% end %>

codecoretest/fulltime/week4/day 17 Rails/amazon/app/views/products/index.html.erb
<h1>ALl products </h1>

<% @products.each do |prod| %>
<div class="col-xs-4">
  <div class="card">
    <img class="card-img-top img-circle m-x-auto d-block" src="<%= prod.image %>" alt="Card image cap">
    <div class="card-block">
      <h5 class="card-title"><%= prod.title %>"</h5>
      <p class="card-text"><%= link_to prod.title, product_path(prod) %>"</p>
      <p class="card-text"><%= prod.description.first(80) %>"</p>
      <a href="<%= product_path(prod) %>" class="btn btn-primary">more detail </a>
    </div>
  </div>



</div>

<% end  %>

codecoretest/fulltime/week4/day 17 Rails/amazon/app/views/products/new.html.erb
<h1>New Product</h1>

<div class="alert alert-success" role="alert">
<%= @product.errors.full_messages.join(", ") %>
</div>
 <%= form_for @product do |f| %>
   <div class="form-group row">
     <%= f.label(:title, class: "col-xs-2 col-form-label") %>
     <div class="col-xs-10">
       <%= f.text_field :title %>
    </div>
   </div>
   <div class="form-group row">
     <%= f.label(:description, class: "col-xs-2 col-form-label") %>
      <div class="col-xs-10">
       <%= f.text_area(:description, class: "form-control")%>
       </div>
   </div>
   <div class="form-group row">
     <%= f.label(:price, class: "col-xs-2 col-form-label") %>
     <div class="col-xs-10">
       <%= f.text_field :price %>
    </div>
   </div>

   <div class="form-group row">
     <%= f.label(:category, class: "col-xs-2 col-form-label") %>
     <div class="col-xs-10">
       <%= f.collection_select :category_id, Category.all, :id , :title  %>
     </div>
   </div>
   <%= f.submit ("Edit Product"), {class: "btn btn-danger col-xs-offset-2"}%>

 <% end %>

codecoretest/fulltime/week4/day 17 Rails/amazon/app/views/products/show.html.erb
<h1><%= @product.title %></h1>
<p><%= @product.description %></p>
<p><%= number_to_currency(@product.price) %></p>
<p><%= @product.created_at %></p>

<%= link_to "Edit" , edit_product_path(@product), class: "btn btn-default" %>
<%= link_to "Delete" , product_path(@product),
                        method: :delete,
                        data: {confirm: "Are you sure?"} ,
                        class: "btn btn-default"
%>

<% if @review.errors.full_messages.join(", ") != "" %>
  <div class="alert alert-warning" role="alert">
    <%= @review.errors.full_messages.join(", ")  %>
  </div>
<% end %>

<%= form_for [@product, @review] do |f| %>
  <div class="">
    <%= f.text_area :body %>
  </div>

  <div class="">
    <%= f.label :start %>

    <%= f.radio_button :star, 1 %>
    <%= f.radio_button :star, 2 %>
    <%= f.radio_button :star, 3 %>
    <%= f.radio_button :star, 4 %>
    <%= f.radio_button :star, 5 %>



    <%#= f.text_field :star %>
  </div>
  <%= f.submit  %>
<% end  %>


<% if @product.reviews.any? %>
  <h2>Review</h2>
  <% @product.reviews.each do |rev| %>
    <%= rev.body %>
    <%= link_to "delete", product_review_path(@product, rev),
                        method: :delete,
                        data: {confirm: "Are you sure?"} %>
    <hr>
  <% end %>
<% end %>